Fix functions w/ internal linkage as template arguments.
MSVC sometimes has problems with passing the address of a function with internal
linkage (free function with "static") as a template argument, generating e.g.
something like

> error C2971: 'classname': template parameter 'FVal':
> '`anonymous-namespace'::proc0': a variable with non-static storage duration
> cannot be used as a non-type argument

The workaround is luckily trivial: Use an anonymous namespace instead of
internal linkage.